name: Build test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17.0'

      - name: Install dependencies
        run: go mod download
      - name : Unit Tests
        run: go test ./
      - name: Build the Go application
        run: go build .